name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      - name: Install ChromeDriver
        run: |
          curl -o chromedriver_win32.zip https://chromedriver.storage.googleapis.com/131.0.6778.6900/chromedriver_win32.zip
          Expand-Archive -Path chromedriver_win32.zip -DestinationPath C:\Tools
          $env:PATH += ";C:\Tools"
        shell: pwsh

      # Build the project
      - name: Build the project
        run: dotnet build --no-restore

      # Run tests
      - name: Run tests
        run: dotnet test --logger "trx;LogFileName=test_results.trx" --no-build

      # Publish Allure results
      - name: Publish Allure results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: bin/Debug/net6.0/allure-results
